export const CONTRACT_ADDRESS = "0x5615dEB798BB3E4dFa0139dFa1b3D433Cc23b72f";

export const ABI = [
  { type: "constructor", inputs: [{ name: "_fee", type: "uint256", internalType: "uint256" }], stateMutability: "nonpayable" },
  {
    type: "function",
    name: "DECIMALS",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "INITIAL_PRICE",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "INIT_SUPPLY",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "K",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "MAX_SUPPLY",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "TARGET",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "buy",
    inputs: [
      { name: "_token", type: "address", internalType: "address" },
      { name: "_amount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "calculateCost",
    inputs: [
      { name: "_currentSupply", type: "uint256", internalType: "uint256" },
      { name: "_tokenAmount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "create",
    inputs: [
      { name: "_name", type: "string", internalType: "string" },
      { name: "_symbol", type: "string", internalType: "string" },
      { name: "_imageUrl", type: "string", internalType: "string" },
      { name: "_description", type: "string", internalType: "string" },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "getTokenAddresses",
    inputs: [],
    outputs: [{ name: "", type: "address[]", internalType: "address[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getTokenDetails",
    inputs: [{ name: "_tokenAddress", type: "address", internalType: "address" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct TokenLaunchPad.TokenDetails",
        components: [
          { name: "token", type: "address", internalType: "address" },
          { name: "name", type: "string", internalType: "string" },
          { name: "creator", type: "address", internalType: "address" },
          { name: "imageUrl", type: "string", internalType: "string" },
          { name: "description", type: "string", internalType: "string" },
          { name: "sold", type: "uint256", internalType: "uint256" },
          { name: "raised", type: "uint256", internalType: "uint256" },
          { name: "isOpen", type: "bool", internalType: "bool" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getTokens",
    inputs: [],
    outputs: [
      {
        name: "tokenDetails",
        type: "tuple[]",
        internalType: "struct TokenLaunchPad.TokenDetails[]",
        components: [
          { name: "token", type: "address", internalType: "address" },
          { name: "name", type: "string", internalType: "string" },
          { name: "creator", type: "address", internalType: "address" },
          { name: "imageUrl", type: "string", internalType: "string" },
          { name: "description", type: "string", internalType: "string" },
          { name: "sold", type: "uint256", internalType: "uint256" },
          { name: "raised", type: "uint256", internalType: "uint256" },
          { name: "isOpen", type: "bool", internalType: "bool" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "i_owner",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "s_fee",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "s_tokenAddresses",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "s_tokenToDetails",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [
      { name: "token", type: "address", internalType: "address" },
      { name: "name", type: "string", internalType: "string" },
      { name: "creator", type: "address", internalType: "address" },
      { name: "imageUrl", type: "string", internalType: "string" },
      { name: "description", type: "string", internalType: "string" },
      { name: "sold", type: "uint256", internalType: "uint256" },
      { name: "raised", type: "uint256", internalType: "uint256" },
      { name: "isOpen", type: "bool", internalType: "bool" },
    ],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "Buy",
    inputs: [
      { name: "token", type: "address", indexed: true, internalType: "address" },
      { name: "amount", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Created",
    inputs: [{ name: "token", type: "address", indexed: true, internalType: "address" }],
    anonymous: false,
  },
  { type: "error", name: "TokenLaunchPad__AmountLessThanFee", inputs: [] },
  { type: "error", name: "TokenLaunchPad__InsufficientETH", inputs: [] },
  { type: "error", name: "TokenLaunchPad__NotEnoughSupply", inputs: [] },
  { type: "error", name: "TokenLaunchPad__SaleClosed", inputs: [] },
  { type: "error", name: "TokenLaunchPad__TokenNotListed", inputs: [] },
];
